name: Build Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-gnu
        override: true

    - name: Install Dependencies
      run: |
        npm install
        npm install @tauri-apps/cli

    - name: Clean previous builds
      run: |
        cd src-tauri
        cargo clean
        if (Test-Path Cargo.lock) { Remove-Item Cargo.lock -Force }
        cd ..

    - name: Build with Tauri
      run: |
        npm install
        npm install @tauri-apps/cli
        # Force clean resource generation
        rm -rf src-tauri/target/x86_64-pc-windows-gnu/release/build/
        npx tauri build --target x86_64-pc-windows-gnu --verbose
      env:
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32-gcc
        RUSTFLAGS: "-C target-feature=+crt-static"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-App
        path: |
          src-tauri/target/x86_64-pc-windows-gnu/release/*.exe
          src-tauri/target/x86_64-pc-windows-gnu/release/bundle/msi/*.msi